### ISSUE TITLE
Upgrade to ramsey/uuid 3.x

### ISSUE THREAD

**Issue by sandrokeil** [prooph/common#48]
Depending on discussion of #47 we should upgrade to `ramsey/uuid: ^3.0` with next major release.

_Note:_ Other prooph components must also be updated.

**Comment by codeliner** [comment]
:+1:

**Comment by basz** [comment]
plz. as `composer install --prefer-dist --no-interaction --optimize-autoloader --no-progress` will fail even with `mattketmo/uuid-2x-bridge:*@dev`.

**Comment by sandrokeil** [comment]
@codeliner What do you think about to bring this with a minor release of the components? We don't change the public API and the beviour is the same? Also the functions are the same, only namespace has changed. If someone uses this version of uuid, they should have it defined as a dependency. /cc @prolic

**Comment by codeliner** [comment]
@basz Why does it fail? Do you have an error msg? /cc @MattKetmo 

@sandrokeil I'd like to stick to the plan and include the upgrade in the next major release. The public API of `Message` interface changes which can cause problems in applications relying on the return type.

**Comment by basz** [comment]
Appearently one needs to include that library into the main project composer.json, Not in the composer.json of a dependency. Once I did that things went as expected again.

**Comment by codeliner** [comment]
good news @basz

**Comment by timiTao** [comment]
Do you have plan to upgrade this to 3.0? Half year later :)

**Comment by codeliner** [comment]
@timiTao Did you try the workaround that is referenced in this issue? 
Yes, the issue is open for a long time because the workaround works good and we need major releases to upgrade but we don't want to release majors just because a dependency has changed its namespace.
To answer your question: https://github.com/prooph/common/pull/56
wip

**Comment by timiTao** [comment]
@codeliner i don't get the workaround 😢  any tips?

for now, i have 

`
        "ramsey/uuid": "~2.9",
        "prooph/event-store": "^6.0",
`

**Comment by basz** [comment]
add this to your composer requirements, and then run composer update

```
"mattketmo/uuid-2x-bridge": "*@dev",
```

**Comment by codeliner** [comment]
@timiTao see this: https://github.com/prooph/common/pull/52#issuecomment-221969430

**Comment by timiTao** [comment]
Worked, thanks 👍
