### ISSUE TITLE
Allow stdClass objects in payload

### ISSUE THREAD

**Issue by codeliner** [prooph/common#54]
Arrays are copied instead of passed by reference. If you ensure that the array only contains arrays and scalar types and you pass such an array to an object that only allows read access you easily get an immutable object (like our message classes)
so far so good, BUT:

``` php
$json = "{}";
$assoc = json_decode($json, true);
if ($json !== json_encode($assoc)) {
  echo "Empty assoc becomes empty json array\n";
}

$stdClassObj = json_decode($json);
if ($json === json_encode($stdClassObj)) {
  echo "Empty stdclass obj becomes empty json object\n";
}
```

This means, that I cannot have a message object that is both: immutable and 100% correctly json encodable/decodable at the same time except I use some kind of deep copy mechanism when passing data into the message and out. I can image the latter influences performance.

What can we do to improve the situation?

**Comment by codeliner** [comment]
IMHO we need to allow \stdClass objects in payload and accept that our messages are not immutable.
Please vote with :+1: and :-1: for this idea!

**Comment by bweston92** [comment]
How will you check all properties are also valid, `get_class_vars` and iterate over them?
Also what if there is a reference to the object it self in there will that cause endless recursion?

**Comment by codeliner** [comment]
I would add an instanceof \stdClass check here: https://github.com/prooph/common/blob/master/src/Messaging/MessageDataAssertion.php#L73
and here: https://github.com/prooph/common/blob/master/src/Messaging/MessageDataAssertion.php#L82

**Comment by bweston92** [comment]
Ok, what happens if I do
```
$obj = new stdClass;
$obj->a = &$obj;
```

How would `assertSubPayload` handle it?

**Comment by prolic** [comment]
`var_dump(json_encode([]));`

and

`var_dump(json_decode('[]', true));`

so how to you come to this?

`$json = "{}";`

**Comment by codeliner** [comment]
@prolic non php system sending a message, for example JS client sends a json body and you turn this into a command payload

**Comment by prolic** [comment]
Can be bypassed very simple:

    if ($json === "{}") { $json = []; }

**Comment by Ocramius** [comment]
I wouldn't allow `stdClass` support at all: it is very error prone and provides no advantages at all. If what you need is immutability, then an `ArrayAccess` implementation is a better (yet more complicated) solution, but please let's not use PHP's ancient (broken) object model.

**Comment by codeliner** [comment]
@prolic yeah of course, but my example only illustrates the problem. In a nested structure it becomes hard to do this type conversation manually and it is impossible to do this a generic way because you simply don't have the information if the property of the nested object is an array or object when it is empty

**Comment by Ocramius** [comment]
Is this just because of json encoding btw? Are there any real world examples on edge-cases that need it?

**Comment by prolic** [comment]
About nesting:

`'{"foo":{}}'` vs `'{"foo":[]}'`, right?

What should the big difference be? Empty array or empty object, I don't care. A getter method on the message object should handle that difference, and decide what do to. I cannot imagine a payload where empty array or empty object make a semantic difference.

**Comment by Ocramius** [comment]
> I cannot imagine a payload where empty array or empty object make a semantic difference.

Same thoughts here, which is why I asked for edge cases

**Comment by codeliner** [comment]
@Ocramius yes, it is because of json encoding. And I run into the issue several times.

consider this:
```php
echo json_encode(['config' => ['optionalOptions' => []]]);
```

´´´javascript
var config = JSON.parse(phpResponse);

config.optionalOptions.enableStrictJsonMode = true; //error wrong type, optionalOptions is an array
´´´

**Comment by codeliner** [comment]
@prolic yeah, as long as your message is only handled by php but a message can be handled by any system, you don't know it so you should ensure that your json encoded message contains correct types.
A JSON-Schema validation will fail on consumer side ...

**Comment by Ocramius** [comment]
Hmm, there are various solutions here:

 * moving to stdClass for everything ("just works" with PHP, but really sucks terribly. Meh.)
 * moving to a proper serializer (which is much much slower, but appropriate)
 * having own ArrayObject-alike structure that implements JsonSerializable (possibly more work, won't pass the `array` type-hints tho)

**Comment by prolic** [comment]
Hard to decide for me, but in general I have a strong feeling against this proposal.
The points of @Ocramius 
 * moving to a proper serializer (which is much much slower, but appropriate)
 * having own ArrayObject-alike structure that implements JsonSerializable (possibly more work, won't pass the array type-hints tho)

seem like a better solution to me.

**Comment by Ocramius** [comment]
Another one: documenting a limitation.

This last one might be a hard one to bite, but it might also be a good temporary solution, waiting until some better approaches emerge. After all, this thread was started only 40 mins ago.

**Comment by codeliner** [comment]
@Ocramius thought about the same: We should add something like that to the documentation: "You should design your message payload/API in a way that empty objects are not possible"

**Comment by codeliner** [comment]
anyway, I'll play with that idea: having own ArrayObject-alike structure that implements JsonSerializable

**Comment by prolic** [comment]
Testet with Zend\Json:

    use Zend\Json\Decoder;
    
    var_dump(Decoder::decode('{"foo":[]}'));
    
    var_dump(Decoder::decode('{"foo":{}}'));
    
    var_dump(Decoder::decode('[]'));
    
    var_dump(Decoder::decode('{}'));

So maybe we just switch to this instead of php's native functions and we are done.

**Comment by codeliner** [comment]
@prolic the problem is with encoding PHP array to JSON (same problem with Zend\Json):

```php
$obj = ['foo' => []];
json_encode($obj); // '{"foo":[]}'

$obj = ['foo' => new \stdClass];
json_encode($obj); // '{"foo":{}}'

$clientObj = json_decode('{"foo":{}}', true);
json_encode($clientObj); // '{"foo":[]}' <-- client gets different structure back: schema is invalid

$clientObj = json_decode('{"foo":{}}');
json_encode($clientObj); // '{"foo":{}}' <-- client gets same structure back: everything ok

$clientObj = json_decode('{"foo":{}}');
$proophCommand = Command::withPayload($clientObj); //Not allowed because $clientObj contains \stdClass object
```

Note: the last example does not throw an exception in the first place (except you ensure it in your message implementation) but when you do:
`$proophMessage = $proophMessage->withAddedMetadata('some_meta', 'some_meta_value')`

**Comment by prolic** [comment]
If we have the role that payload has to be array or scalar, this implies
that also in other languages those rules apply. The leads to {"foo":{}}
being invalid payload.
On the other hand {"foo":[]} would be valid and the stdclass on the payload
(not subpayload) can be converted to array.
Am 06.06.2016 18:41 schrieb "Alexander Miertsch" <notifications@github.com>:

**Comment by codeliner** [comment]
we have the rule that everything insight the payload must be an array or scalar:  https://github.com/prooph/common/blob/master/src/Messaging/MessageDataAssertion.php#L82

**Comment by codeliner** [comment]
PHP array can have a numeric index = JSON array 
PHP array can be a hash map (assoc array) = JSON object

This means, that our definition of an array is not precise enough because we (json_encode) cannot distinguish between these two if PHP array is empty

**Comment by prolic** [comment]
Ok but we can add a test if array is assoc or not and use this info before
json encoding.
Am 06.06.2016 19:17 schrieb "Alexander Miertsch" <notifications@github.com>:

**Comment by Ocramius** [comment]
Yes, that is indeed the reason for going with an alternate data-structure. `stdClass` being a compromise for performance reasons (works well with internals).

@codeliner is the write to a hashmap the only scenario where this fails?

**Comment by prolic** [comment]
@Codeliner can you write a test case that fails now and we can try
different implementations to turn the testa green again while testing
performance, too
Am 06.06.2016 19:20 schrieb "Marco Pivetta" <notifications@github.com>:

**Comment by prolic** [comment]
About stdclass and immutability, i am just writing fast here without
thinking much, ain't it possible to always use clone so you cannot modify
the payload from outside?
Am 06.06.2016 19:24 schrieb "Sascha-Oliver Prolic" <
saschaprolic@googlemail.com>:

**Comment by codeliner** [comment]
@prolic only deep clone would work with recursive clone. There is also https://github.com/myclabs/DeepCopy by @mnapoli to handle circular references.
Good idea with the test case. I'll provide one or two later.

@Ocramius yeah, only problem is that an empty assoc should result in a JSON object and an empty array should result in a JSON array: `$amIAssocOrArray = []; //?`
If you have a schema definition at hand (for example a JSON-Schema) you could inspect the schema and determine the correct type, but this is again a performance nightmare.

**Comment by codeliner** [comment]
I turned back to my problem space with the feedback collected here and thought about the problem again. I agree now that an empty object in a data structure is an edge case and can be avoided easily.

A nested object without any properties can be replaced by null to express the same state:
`'{"foo": {}}'` => `'{"foo": null}'`
The client just need to know that but that is a matter of good API documentation.

It is simply too much work required to improve the situation. We should add a note or warning in the docs and link to this issue. I keep it open until docs are updated, but I don't think that we need to investigate further work. It is not worth the effort. 
Thx @bweston92 , @prolic , @Ocramius for feedback :+1:

**Comment by Ocramius** [comment]
Glad that the simplest workaround was picked for now: huge rabbit-hole otherwise :-)

**Comment by bweston92** [comment]
Still add tests for array's with circular references?

**Comment by codeliner** [comment]
@bweston92 yeah, will do

**Comment by tensor146** [comment]
Strongly not agree: null is null, empty object is empty object. Its logically two different things and idea just always use null looks incorrect for me =/
ArrayObject looks pretty good compromise, but for now its impossible too: its not scalar or array..

**Comment by codeliner** [comment]
@tensor146 That's true, but we decided to not introduce more than needed complexity. We have this mismatch in PHP when working with arrays and json_encode and while there are solutions available no of them is perfect. You can read the details in the history of the issue.

ArrayObject is not an option because it is passed by reference (unlike a real array) so we would lose the simple semi-immutable structure of our message objects. Immutability (or semi-immutability) is more important for us than null vs. empty object.
