### ISSUE TITLE
Remove ActionEventListener interface

### ISSUE THREAD

**Issue by prolic** [prooph/common#55]
RFC for prooph/common 4.0
- remove \Prooph\Common\Event\ActionEventListener

reason: callable is just fine enough, this would lead to strict type hints and return values. No messing up with phpdoc and callable|ActionEventListener and all these additional checks in a method like: 

`if (! $listener instanceof ActionEventListener && !is_callable($listener)) {`

thoughts? /cc @codeliner @sandrokeil @bweston92

**Comment by codeliner** [comment]
+1
