### ISSUE TITLE
Only array and scalar in event objects

### ISSUE THREAD

**Issue by mumia** [prooph/common#77]
I'm aware this project will be deprecated, but I was wondering why would we not allow objects in the event's payload.

In my opinion the event object should be able to hold domain objects and get them serialised when persisting it or queueing it.

https://github.com/prooph/common/blob/master/src/Messaging/MessageDataAssertion.php#L71

Am I wrong in this assumption?

**Comment by prolic** [comment]
see here https://github.com/prooph/common/issues/54
